language: cpp
dist: xenial

addons:
  apt:
    update: true
    packages:
      - wget

env:
  - LLVM_HOME=/tmp/llvm/bin/

compiler:
  - gcc

script:
  - wget -q -O llvm.tar.xz https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz 
  - mkdir -p /tmp/llvm && tar -C /tmp/llvm -xf llvm.tar.xz
  - mkdir build && cd build
  - cmake .. && sudo make install
  - cd ../test && cmake .
  - make 
